const TOTAL=20,MAX_LEVEL=20,KEY='dodge-read-decision-v1';
const actions=['catch','dodgeLeft','dodgeRight','stay'];
const labels={catch:'捕る',dodgeLeft:'左へ避ける',dodgeRight:'右へ避ける',stay:'動かない'};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const screens={home:$('#home'),game:$('#game'),result:$('#result')},canvas=$('#canvas'),ctx=canvas.getContext('2d');
let session=null,state=null,raf=0,w=0,h=0,portraitDismissed=false,answerTimer=0;
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function difficulty(level){level=clamp(Math.round(level),1,MAX_LEVEL);return{level,visibleFraction:clamp(.58-(level-1)*.012,.32,.58),total:1130-(level-1)*8,answerLimit:1050-(level-1)*15,startSpread:.20+(level-1)*.004,curve:.018+(level-1)*.0025,borderBias:clamp(.18+(level-1)*.021,.18,.56)}}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{best:0,sessions:0,level:10}}catch{return{best:0,sessions:0,level:10}}}
function save(score,endLevel){const p=load(),isBest=score>(p.best||0),next=clamp(endLevel-(score<10?1:0),1,MAX_LEVEL);localStorage.setItem(KEY,JSON.stringify({best:Math.max(p.best||0,score),sessions:(p.sessions||0)+1,level:next}));return isBest}
function show(name){Object.entries(screens).forEach(([k,n])=>n.classList.toggle('active',k===name));if(name!=='game'){cancelAnimationFrame(raf);clearTimeout(answerTimer)}refreshPortrait()}
function refreshStats(){const p=load();$('#best').textContent=p.sessions?`${p.best} / ${TOTAL}`:`-- / ${TOTAL}`;$('#sessions').textContent=`${p.sessions||0}回`;$('#startLevel').textContent=`Lv.${clamp(p.level||10,1,MAX_LEVEL)}`}
function targetFor(action,d){const edge=Math.random()<d.borderBias,j=(Math.random()-.5)*.018;if(action==='catch')return edge?(Math.random()<.5?.455:.545)+j:.5+(Math.random()-.5)*.055;if(action==='dodgeRight')return edge?.43+j:.365+(Math.random()-.5)*.07;if(action==='dodgeLeft')return edge?.57+j:.635+(Math.random()-.5)*.07;return Math.random()<.5?(edge?.285+j:.17+(Math.random()-.5)*.08):(edge?.715+j:.83+(Math.random()-.5)*.08)}
function makeTrial(level,action){const d=difficulty(level),targetX=clamp(targetFor(action,d),.05,.95),startX=.5+(Math.random()-.5)*d.startSpread*2,delta=targetX-startX,curve=(Math.random()<.5?-1:1)*d.curve*(.4+Math.random()*.6),c1=clamp(startX+delta*.28+curve,.06,.94),c2=clamp(startX+delta*.73+curve*.25,.06,.94);return{id:crypto.randomUUID?crypto.randomUUID():String(Math.random()),action,level:d.level,startX,targetX,c1,c2,visible:d.total*d.visibleFraction,total:d.total,answerLimit:d.answerLimit}}
function bezier(a,b,c,d,t){const u=1-t;return u*u*u*a+3*u*u*t*b+3*u*t*t*c+t*t*t*d}
function position(t,p){p=clamp(p,0,1);const depth=1-Math.pow(1-p,1.48);return{x:clamp(bezier(t.startX,t.c1,t.c2,t.targetX,depth),.03,.97),y:.18+.69*Math.pow(depth,1.25),scale:.20+1.28*Math.pow(depth,1.72)}}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);w=Math.max(1,r.width);h=Math.max(1,r.height);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);draw()}
function court(){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#122844');g.addColorStop(.47,'#0a1a2f');g.addColorStop(1,'#06101d');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);const hy=h*.17;ctx.strokeStyle='rgba(166,205,255,.18)';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(w*.49,hy);ctx.lineTo(w*.05,h);ctx.moveTo(w*.51,hy);ctx.lineTo(w*.95,h);ctx.stroke();for(let i=1;i<=6;i++){const p=i/7,y=hy+Math.pow(p,1.58)*(h-hy),half=14+Math.pow(p,1.4)*w*.45;ctx.strokeStyle='rgba(255,255,255,.09)';ctx.beginPath();ctx.moveTo(w/2-half,y);ctx.lineTo(w/2+half,y);ctx.stroke()}const y=h*.87;ctx.fillStyle='rgba(103,213,255,.08)';ctx.fillRect(w*.455,y-22,w*.09,44);ctx.fillStyle='rgba(255,218,54,.07)';ctx.fillRect(w*.285,y-22,w*.17,44);ctx.fillRect(w*.545,y-22,w*.17,44);ctx.strokeStyle='rgba(255,255,255,.25)';ctx.lineWidth=2;ctx.beginPath();ctx.arc(w*.5,y-45,14,0,Math.PI*2);ctx.moveTo(w*.5,y-31);ctx.lineTo(w*.5,y+14);ctx.moveTo(w*.5,y-15);ctx.lineTo(w*.47,y+6);ctx.moveTo(w*.5,y-15);ctx.lineTo(w*.53,y+6);ctx.moveTo(w*.5,y+14);ctx.lineTo(w*.475,y+39);ctx.moveTo(w*.5,y+14);ctx.lineTo(w*.525,y+39);ctx.stroke()}
function ball(pos,a=1,ghost=false){const x=pos.x*w,y=pos.y*h,r=Math.max(5,Math.min(w,h)*.034*pos.scale);ctx.save();ctx.globalAlpha=a;const g=ctx.createRadialGradient(x-r*.34,y-r*.4,r*.1,x,y,r);g.addColorStop(0,ghost?'#effaff':'#fffad0');g.addColorStop(.52,ghost?'#6fd4ff':'#ffe044');g.addColorStop(1,ghost?'#13618c':'#e46d00');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle=ghost?'#053d60aa':'#60270099';ctx.lineWidth=Math.max(1,r*.075);ctx.beginPath();ctx.arc(x,y,r*.7,-.8,1.1);ctx.stroke();ctx.beginPath();ctx.arc(x,y,r*.67,2.05,4.2);ctx.stroke();ctx.restore()}
function targetMarker(t){const y=h*.87,x=t.targetX*w;ctx.save();ctx.strokeStyle='#ffda36';ctx.lineWidth=2.5;ctx.setLineDash([5,5]);ctx.beginPath();ctx.arc(x,y,18,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.restore()}
function draw(now=performance.now()){if(!w||!h)return;court();if(state){const t=state.t;if(state.phase==='flying'){const e=now-state.started,p=Math.min(1,e/t.total);if(e<=t.visible)ball(position(t,p))}else if(state.phase==='answering'){const remain=clamp(1-(now-state.answerOpened)/t.answerLimit,0,1);$('#timer i').style.transform=`scaleX(${remain})`}else if(state.phase==='revealing'){const e=now-state.revealStart,d=650,sp=t.visible/t.total,rp=Math.min(1,e/d),p=sp+(1-sp)*rp;for(let i=6;i>=1;i--)ball(position(t,Math.max(sp,p-i*.023)),.05+(6-i)*.025,true);ball(position(t,p),.95,true);if(rp>.7)targetMarker(t);if(e>=d&&!state.done){state.done=true;setTimeout(next,360)}}}if($('#game').classList.contains('active'))raf=requestAnimationFrame(draw)}
function enable(v){$$('.decision').forEach(b=>b.disabled=!v)}
function header(){$('#number').textContent=Math.min(session.index+1,TOTAL);$('#bar').style.width=`${session.index/TOTAL*100}%`;$('#level').textContent=session.level}
async function countdown(){for(const x of ['3','2','1']){$('#count').textContent=x;await new Promise(r=>setTimeout(r,380))}$('#count').textContent=''}
function buildSchedule(){return shuffle(actions.flatMap(a=>Array(5).fill(a)))}
async function start(){cancelAnimationFrame(raf);clearTimeout(answerTimer);const startLevel=clamp(load().level||10,1,MAX_LEVEL);session={index:0,level:startLevel,results:[],block:[],schedule:buildSchedule()};state=null;portraitDismissed=false;show('game');requestAnimationFrame(()=>{resize();header()});enable(false);$('#feedback').className='feedback';$('#instruction').textContent='中央の＋を見ろ';$('#focus').style.opacity='1';$('#timer').className='timer';await countdown();launch()}
function launch(){if(!session||session.index>=TOTAL)return finish();header();enable(false);$('#feedback').className='feedback';$('#feedback').textContent='';$('#timer').className='timer';$('#instruction').textContent='軌道を読む';$('#focus').style.opacity='.55';const t=makeTrial(session.level,session.schedule[session.index]);state={t,phase:'flying',started:performance.now(),answerOpened:0,revealStart:0,done:false};cancelAnimationFrame(raf);raf=requestAnimationFrame(draw);setTimeout(()=>{if(!state||state.t.id!==t.id||state.phase!=='flying')return;state.phase='answering';state.answerOpened=performance.now();$('#instruction').textContent='行動を選べ';$('#focus').style.opacity='0';$('#timer').className='timer show';enable(true);answerTimer=setTimeout(()=>timeout(t.id),t.answerLimit)},t.visible)}
function isReverse(chosen,correct){return chosen==='dodgeLeft'&&correct==='dodgeRight'||chosen==='dodgeRight'&&correct==='dodgeLeft'}
function resolve(chosen,timedOut=false){if(!state||state.phase!=='answering')return;clearTimeout(answerTimer);enable(false);const t=state.t,ms=timedOut?t.answerLimit:Math.round(performance.now()-state.answerOpened),correct=!timedOut&&chosen===t.action,reverse=!timedOut&&isReverse(chosen,t.action),f=$('#feedback');f.textContent=timedOut?'TIME OUT':correct?'EXACT!':`正解：${labels[t.action]}`;f.className=`feedback show ${correct?'good':'bad'}`;$('#instruction').textContent='判断を検証';$('#timer').className='timer';session.results.push({action:t.action,chosen,correct,reverse,ms,level:t.level,timedOut});session.block.push(correct);if(session.block.length===5){const c=session.block.filter(Boolean).length;if(c>=4)session.level=clamp(session.level+1,1,MAX_LEVEL);else if(c<=2)session.level=clamp(session.level-1,1,MAX_LEVEL);session.block=[]}state.phase='revealing';state.revealStart=performance.now()}
function timeout(id){if(state&&state.t.id===id&&state.phase==='answering')resolve(null,true)}
function next(){if(!session)return;session.index++;session.index>=TOTAL?finish():launch()}
function median(a){if(!a.length)return 0;a=[...a].sort((x,y)=>x-y);const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function actionRate(action){const a=session.results.filter(x=>x.action===action);return a.length?Math.round(a.filter(x=>x.correct).length/a.length*100):0}
function finish(){cancelAnimationFrame(raf);clearTimeout(answerTimer);enable(false);const exact=session.results.filter(x=>x.correct).length,valid=session.results.filter(x=>!x.timedOut),ms=Math.round(median(valid.map(x=>x.ms))),reverse=session.results.filter(x=>x.reverse).length,timeouts=session.results.filter(x=>x.timedOut).length,endLevel=session.level,isBest=save(exact,endLevel);$('#score').textContent=exact;$('#reaction').textContent=valid.length?`${ms} ms`:'-- ms';$('#endLevel').textContent=`Lv.${endLevel}`;$('#reverse').textContent=`${reverse}回`;$('#timeouts').textContent=`${timeouts}回`;$('#message').textContent=exact>=17?'ELITE。軌道と行動選択が高精度で連動しています。':exact>=13?'高水準。外れる球への不要反応をさらに減らそう。':exact>=9?'PRO負荷に適応中。球を追う前に到達位置を決めよう。':'判断を急がず、身体の範囲と軌道を分けて見よう。';$('#actionRates').innerHTML=actions.map(a=>`<div><span>${labels[a]}</span><strong>${actionRate(a)}%</strong></div>`).join('');$('#newBest').hidden=!isBest;state=null;show('result');refreshStats()}
function home(){cancelAnimationFrame(raf);clearTimeout(answerTimer);session=null;state=null;enable(false);show('home');refreshStats()}
function refreshPortrait(){const p=innerHeight>innerWidth&&innerWidth<720&&!portraitDismissed&&$('#game').classList.contains('active');$('#portrait').style.display=p?'flex':'none'}
$('#start').onclick=start;$('#retry').onclick=start;$('#homeBtn').onclick=home;$('#quit').onclick=()=>{if(confirm('トレーニングを終了しますか？'))home()};$('#continue').onclick=()=>{portraitDismissed=true;refreshPortrait()};$$('.decision').forEach(b=>b.onclick=()=>resolve(b.dataset.action,false));addEventListener('resize',()=>{refreshPortrait();if($('#game').classList.contains('active'))resize()});addEventListener('orientationchange',()=>setTimeout(()=>{portraitDismissed=false;refreshPortrait();resize()},200));refreshStats();
