const TOTAL=20,MAX_LEVEL=20,KEY='dodge-read-pro-v2',zones=[0,1,2,3,4];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const screens={home:$('#home'),game:$('#game'),result:$('#result')},canvas=$('#canvas'),ctx=canvas.getContext('2d');
let session=null,state=null,raf=0,w=0,h=0,portraitDismissed=false,answerTimer=0;
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
const shuffle=a=>{a=[...a];for(let i=a.length-1;i>0;i--){const j=Math.floor(Math.random()*(i+1));[a[i],a[j]]=[a[j],a[i]]}return a};
function difficulty(level){level=clamp(Math.round(level),1,MAX_LEVEL);return{level,visibleFraction:clamp(.56-(level-1)*.013,.30,.56),total:1110-(level-1)*9,answerLimit:970-(level-1)*14,startSpread:.17+(level-1)*.0045,curve:.018+(level-1)*.0028,boundaryBias:clamp(.14+(level-1)*.023,.14,.58)}}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{best:0,sessions:0,level:10}}catch{return{best:0,sessions:0,level:10}}}
function save(score,endLevel){const p=load(),isBest=score>(p.best||0),next=clamp(endLevel-(score<10?1:0),1,MAX_LEVEL);localStorage.setItem(KEY,JSON.stringify({best:Math.max(p.best||0,score),sessions:(p.sessions||0)+1,level:next}));return isBest}
function show(name){Object.entries(screens).forEach(([k,n])=>n.classList.toggle('active',k===name));if(name!=='game'){cancelAnimationFrame(raf);clearTimeout(answerTimer)}refreshPortrait()}
function refreshStats(){const p=load();$('#best').textContent=p.sessions?`${p.best} / ${TOTAL}`:`-- / ${TOTAL}`;$('#sessions').textContent=`${p.sessions||0}回`;$('#startLevel').textContent=`Lv.${clamp(p.level||10,1,MAX_LEVEL)}`}
function zoneBounds(z){const min=.08+z*.168,max=min+.168;return{min,max,center:(min+max)/2}}
function targetForZone(z,d){const b=zoneBounds(z),margin=.014,nearBoundary=Math.random()<d.boundaryBias;let x;if(nearBoundary){const right=Math.random()<.5;x=right?b.max-margin:b.min+margin;x+=(Math.random()-.5)*.016}else{x=b.center+(Math.random()-.5)*.07}return clamp(x,b.min+margin,b.max-margin)}
function makeTrial(level,zone){const d=difficulty(level),targetX=targetForZone(zone,d),startX=.5+(Math.random()-.5)*d.startSpread*2,delta=targetX-startX,curve=(Math.random()<.5?-1:1)*d.curve*(.45+Math.random()*.55),c1=clamp(startX+delta*.30+curve,.07,.93),c2=clamp(startX+delta*.72+curve*.28,.07,.93);return{id:crypto.randomUUID?crypto.randomUUID():String(Math.random()),zone,level:d.level,startX,targetX,c1,c2,visible:d.total*d.visibleFraction,total:d.total,answerLimit:d.answerLimit}}
function bezier(a,b,c,d,t){const u=1-t;return u*u*u*a+3*u*u*t*b+3*u*t*t*c+t*t*t*d}
function position(t,p){p=clamp(p,0,1);const depth=1-Math.pow(1-p,1.48);return{x:clamp(bezier(t.startX,t.c1,t.c2,t.targetX,depth),.03,.97),y:.19+.67*Math.pow(depth,1.26),scale:.20+1.22*Math.pow(depth,1.72)}}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);w=Math.max(1,r.width);h=Math.max(1,r.height);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);draw()}
function court(){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#122844');g.addColorStop(.47,'#0a1a2f');g.addColorStop(1,'#06101d');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);const hy=h*.17;ctx.strokeStyle='rgba(166,205,255,.18)';ctx.lineWidth=1.5;ctx.beginPath();ctx.moveTo(w*.49,hy);ctx.lineTo(w*.05,h);ctx.moveTo(w*.51,hy);ctx.lineTo(w*.95,h);ctx.stroke();for(let i=1;i<=6;i++){const p=i/7,y=hy+Math.pow(p,1.58)*(h-hy),half=14+Math.pow(p,1.4)*w*.45;ctx.strokeStyle='rgba(255,255,255,.09)';ctx.beginPath();ctx.moveTo(w/2-half,y);ctx.lineTo(w/2+half,y);ctx.stroke()}const y=h*.86;for(let z=0;z<5;z++){const b=zoneBounds(z),x=b.min*w,ww=(b.max-b.min)*w;ctx.fillStyle=z%2?'rgba(103,213,255,.035)':'rgba(255,255,255,.025)';ctx.fillRect(x,y-9,ww,18);ctx.strokeStyle='rgba(143,214,255,.18)';ctx.strokeRect(x,y-9,ww,18);ctx.fillStyle='rgba(210,231,255,.42)';ctx.font='700 10px system-ui';ctx.textAlign='center';ctx.fillText(String(z+1),(b.center)*w,y+4)}}
function ball(pos,a=1,ghost=false){const x=pos.x*w,y=pos.y*h,r=Math.max(5,Math.min(w,h)*.034*pos.scale);ctx.save();ctx.globalAlpha=a;const shadow=ctx.createRadialGradient(x,y+r*1.25,0,x,y+r*1.25,r*1.55);shadow.addColorStop(0,'#0008');shadow.addColorStop(1,'#0000');ctx.fillStyle=shadow;ctx.beginPath();ctx.ellipse(x,y+r*1.25,r*1.55,r*.4,0,0,Math.PI*2);ctx.fill();const g=ctx.createRadialGradient(x-r*.34,y-r*.4,r*.1,x,y,r);g.addColorStop(0,ghost?'#effaff':'#fffad0');g.addColorStop(.52,ghost?'#6fd4ff':'#ffe044');g.addColorStop(1,ghost?'#13618c':'#e46d00');ctx.fillStyle=g;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();ctx.strokeStyle=ghost?'#053d60aa':'#60270099';ctx.lineWidth=Math.max(1,r*.075);ctx.beginPath();ctx.arc(x,y,r*.7,-.8,1.1);ctx.stroke();ctx.beginPath();ctx.arc(x,y,r*.67,2.05,4.2);ctx.stroke();ctx.restore()}
function targetMarker(t){const b=zoneBounds(t.zone),x=t.targetX*w,y=h*.86;ctx.save();ctx.fillStyle='rgba(255,218,54,.12)';ctx.fillRect(b.min*w,y-18,(b.max-b.min)*w,36);ctx.strokeStyle='#ffda36';ctx.lineWidth=2.5;ctx.setLineDash([5,5]);ctx.beginPath();ctx.arc(x,y,18,0,Math.PI*2);ctx.stroke();ctx.setLineDash([]);ctx.restore()}
function draw(now=performance.now()){if(!w||!h)return;court();if(state){const t=state.t;if(state.phase==='flying'){const e=now-state.started,p=Math.min(1,e/t.total);if(e<=t.visible)ball(position(t,p))}else if(state.phase==='answering'){const remain=clamp(1-(now-state.answerOpened)/t.answerLimit,0,1);$('#timer i').style.transform=`scaleX(${remain})`}else if(state.phase==='revealing'){const e=now-state.revealStart,d=650,sp=t.visible/t.total,rp=Math.min(1,e/d),p=sp+(1-sp)*rp;for(let i=6;i>=1;i--)ball(position(t,Math.max(sp,p-i*.023)),.05+(6-i)*.025,true);ball(position(t,p),.95,true);if(rp>.7)targetMarker(t);if(e>=d&&!state.done){state.done=true;setTimeout(next,360)}}}if($('#game').classList.contains('active'))raf=requestAnimationFrame(draw)}
function enable(v){$$('.answer').forEach(b=>b.disabled=!v)}
function header(){$('#number').textContent=Math.min(session.index+1,TOTAL);$('#bar').style.width=`${session.index/TOTAL*100}%`;$('#level').textContent=session.level}
async function countdown(){for(const x of ['3','2','1']){$('#count').textContent=x;await new Promise(r=>setTimeout(r,380))}$('#count').textContent=''}
function buildSchedule(){return shuffle(zones.flatMap(z=>Array(4).fill(z)))}
async function start(){cancelAnimationFrame(raf);clearTimeout(answerTimer);const startLevel=clamp(load().level||10,1,MAX_LEVEL);session={index:0,level:startLevel,results:[],block:[],schedule:buildSchedule()};state=null;portraitDismissed=false;show('game');requestAnimationFrame(()=>{resize();header()});enable(false);$('#feedback').className='feedback';$('#instruction').textContent='中央の＋を見ろ';$('#focus').style.opacity='1';$('#timer').className='timer';await countdown();launch()}
function launch(){if(!session||session.index>=TOTAL)return finish();header();enable(false);$('#feedback').className='feedback';$('#feedback').textContent='';$('#timer').className='timer';$('#instruction').textContent='初動を読む';$('#focus').style.opacity='.55';const t=makeTrial(session.level,session.schedule[session.index]);state={t,phase:'flying',started:performance.now(),answerOpened:0,revealStart:0,done:false};cancelAnimationFrame(raf);raf=requestAnimationFrame(draw);setTimeout(()=>{if(!state||state.t.id!==t.id||state.phase!=='flying')return;state.phase='answering';state.answerOpened=performance.now();$('#instruction').textContent='到達ゾーンを選べ';$('#focus').style.opacity='0';$('#timer').className='timer show';enable(true);answerTimer=setTimeout(()=>timeout(t.id),t.answerLimit)},t.visible)}
function resolve(chosen,timedOut=false){if(!state||state.phase!=='answering')return;clearTimeout(answerTimer);enable(false);const t=state.t,ms=timedOut?t.answerLimit:Math.round(performance.now()-state.answerOpened),distance=timedOut?99:Math.abs(chosen-t.zone),correct=distance===0,f=$('#feedback');f.textContent=timedOut?'TIME OUT':correct?'EXACT!':distance===1?'1ゾーン差':`正解は ${t.zone+1}`;f.className=`feedback show ${correct?'good':'bad'}`;$('#instruction').textContent='軌道を検証';$('#timer').className='timer';session.results.push({zone:t.zone,chosen,correct,distance,ms,level:t.level,timedOut});session.block.push(correct);if(session.block.length===5){const c=session.block.filter(Boolean).length;if(c>=4)session.level=clamp(session.level+1,1,MAX_LEVEL);else if(c<=2)session.level=clamp(session.level-1,1,MAX_LEVEL);session.block=[]}state.phase='revealing';state.revealStart=performance.now()}
function timeout(id){if(state&&state.t.id===id&&state.phase==='answering')resolve(null,true)}
function next(){if(!session)return;session.index++;session.index>=TOTAL?finish():launch()}
function median(a){if(!a.length)return 0;a=[...a].sort((x,y)=>x-y);const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function zoneRate(z){const a=session.results.filter(x=>x.zone===z);return a.length?Math.round(a.filter(x=>x.correct).length/a.length*100):0}
function finish(){cancelAnimationFrame(raf);clearTimeout(answerTimer);enable(false);const exact=session.results.filter(x=>x.correct).length,valid=session.results.filter(x=>!x.timedOut),ms=Math.round(median(valid.map(x=>x.ms))),near=session.results.filter(x=>x.distance===1).length,timeouts=session.results.filter(x=>x.timedOut).length,endLevel=session.level,isBest=save(exact,endLevel);$('#score').textContent=exact;$('#reaction').textContent=valid.length?`${ms} ms`:'-- ms';$('#endLevel').textContent=`Lv.${endLevel}`;$('#nearMiss').textContent=`${near}回`;$('#timeouts').textContent=`${timeouts}回`;$('#message').textContent=exact>=17?'ELITE。初動から高精度で到達点を読めています。':exact>=13?'高水準。境界付近の判断をさらに研ぎ澄まそう。':exact>=9?'PRO負荷に適応中。球の大きさではなく横移動量を読もう。':'この難度で伸ばす価値がある。初動の角度と加速を分けて見る。';$('#zoneRates').innerHTML=zones.map(z=>`<div><span>ZONE ${z+1}</span><strong>${zoneRate(z)}%</strong></div>`).join('');$('#newBest').hidden=!isBest;state=null;show('result');refreshStats()}
function home(){cancelAnimationFrame(raf);clearTimeout(answerTimer);session=null;state=null;enable(false);show('home');refreshStats()}
function refreshPortrait(){const p=innerHeight>innerWidth&&innerWidth<720&&!portraitDismissed&&$('#game').classList.contains('active');$('#portrait').style.display=p?'flex':'none'}
$('#start').onclick=start;$('#retry').onclick=start;$('#homeBtn').onclick=home;$('#quit').onclick=()=>{if(confirm('トレーニングを終了しますか？'))home()};$('#continue').onclick=()=>{portraitDismissed=true;refreshPortrait()};$$('.answer').forEach(b=>b.onclick=()=>resolve(Number(b.dataset.zone),false));addEventListener('resize',()=>{refreshPortrait();if($('#game').classList.contains('active'))resize()});addEventListener('orientationchange',()=>setTimeout(()=>{portraitDismissed=false;refreshPortrait();resize()},200));refreshStats();
