const TOTAL=20,MAX_LEVEL=20,KEY='dodge-read-rondo-v1';
const $=s=>document.querySelector(s);
const screens={home:$('#home'),game:$('#game'),result:$('#result')},canvas=$('#canvas'),ctx=canvas.getContext('2d');
let session=null,state=null,raf=0,w=0,h=0,lastFrame=0,decisionTimer=0,portraitDismissed=false;
const clamp=(v,a,b)=>Math.min(b,Math.max(a,v));
function difficulty(level){level=clamp(Math.round(level),1,MAX_LEVEL);return{level,defenders:level>=11?2:1,defenderSpeed:.20+(level-1)*.012,decisionLimit:2100-(level-1)*48,passSpeed:.92+(level-1)*.018,interceptRadius:.058+(level-1)*.0016,pressBias:.38+(level-1)*.018}}
function load(){try{return JSON.parse(localStorage.getItem(KEY))||{best:0,sessions:0,level:8}}catch{return{best:0,sessions:0,level:8}}}
function save(score,endLevel){const p=load(),isBest=score>(p.best||0),next=clamp(endLevel-(score<10?1:0),1,MAX_LEVEL);localStorage.setItem(KEY,JSON.stringify({best:Math.max(p.best||0,score),sessions:(p.sessions||0)+1,level:next}));return isBest}
function show(name){Object.entries(screens).forEach(([k,n])=>n.classList.toggle('active',k===name));if(name!=='game'){cancelAnimationFrame(raf);clearTimeout(decisionTimer)}refreshPortrait()}
function refreshStats(){const p=load();$('#best').textContent=p.sessions?`${p.best} / ${TOTAL}`:`-- / ${TOTAL}`;$('#sessions').textContent=`${p.sessions||0}回`;$('#startLevel').textContent=`Lv.${clamp(p.level||8,1,MAX_LEVEL)}`}
function resize(){const r=canvas.getBoundingClientRect(),d=Math.min(devicePixelRatio||1,2);w=Math.max(1,r.width);h=Math.max(1,r.height);canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);draw(performance.now())}
function field(){const g=ctx.createLinearGradient(0,0,0,h);g.addColorStop(0,'#153451');g.addColorStop(1,'#071421');ctx.fillStyle=g;ctx.fillRect(0,0,w,h);const pad=Math.min(w,h)*.08;ctx.strokeStyle='rgba(174,218,255,.30)';ctx.lineWidth=2;ctx.strokeRect(pad,pad,w-pad*2,h-pad*2);ctx.strokeStyle='rgba(255,255,255,.10)';ctx.setLineDash([7,7]);ctx.strokeRect(pad*1.65,pad*1.55,w-pad*3.3,h-pad*3.1);ctx.setLineDash([])}
function playerSpots(){const px=Math.min(w,h)*.105,py=Math.min(w,h)*.13;return[{x:px,y:py},{x:w-px,y:py},{x:w-px,y:h-py},{x:px,y:h-py}]}
function makeDefenders(d){const count=d.defenders,arr=[];for(let i=0;i<count;i++){const a=(i/count)*Math.PI*2+Math.random()*.8,r=Math.min(w,h)*(.08+Math.random()*.08);arr.push({x:w/2+Math.cos(a)*r,y:h/2+Math.sin(a)*r,vx:0,vy:0})}return arr}
function makeTrial(level,holder){const d=difficulty(level);return{id:crypto.randomUUID?crypto.randomUUID():String(Math.random()),d,holder,players:playerSpots(),defenders:makeDefenders(d),phase:'choosing',opened:performance.now(),pass:null,resolved:false}}
function nearestPoint(ax,ay,bx,by,px,py){const dx=bx-ax,dy=by-ay,l=dx*dx+dy*dy||1,t=clamp(((px-ax)*dx+(py-ay)*dy)/l,0,1);return{x:ax+dx*t,y:ay+dy*t,t}}
function moveDefenders(dt){if(!state||!state.t||state.t.phase==='done')return;const t=state.t,d=t.d,holder=t.players[t.holder];for(let i=0;i<t.defenders.length;i++){const def=t.defenders[i];let tx=holder.x,ty=holder.y;if(t.phase==='passing'&&t.pass){const from=t.players[t.pass.from],to=t.players[t.pass.to],p=nearestPoint(from.x,from.y,to.x,to.y,def.x,def.y);tx=p.x;ty=p.y}else{const targets=t.players.map((p,index)=>({index,p,dist:Math.hypot(p.x-def.x,p.y-def.y)})).filter(x=>x.index!==t.holder).sort((a,b)=>a.dist-b.dist);const cover=targets[i%targets.length]?.p;if(cover){tx=holder.x+(cover.x-holder.x)*d.pressBias;ty=holder.y+(cover.y-holder.y)*d.pressBias}}const dx=tx-def.x,dy=ty-def.y,len=Math.hypot(dx,dy)||1,speed=Math.min(w,h)*d.defenderSpeed;def.vx=dx/len*speed;def.vy=dy/len*speed;def.x+=def.vx*dt;def.y+=def.vy*dt;const margin=Math.min(w,h)*.12;def.x=clamp(def.x,margin,w-margin);def.y=clamp(def.y,margin,h-margin)}}
function circle(x,y,r,fill,stroke='#0000',line=2){ctx.fillStyle=fill;ctx.beginPath();ctx.arc(x,y,r,0,Math.PI*2);ctx.fill();if(stroke!=='#0000'){ctx.strokeStyle=stroke;ctx.lineWidth=line;ctx.stroke()}}
function drawPlayer(p,index){const holder=state?.t?.holder===index,r=Math.max(18,Math.min(w,h)*.045);circle(p.x,p.y,r,holder?'#ffda36':'#67d5ff',holder?'#fff3a0':'#bcecff',3);ctx.fillStyle=holder?'#312000':'#06121e';ctx.font=`900 ${Math.max(13,r*.72)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText(index+1,p.x,p.y);if(holder){circle(p.x,p.y+r+10,5,'#ffda36')}}
function drawDefender(d){const r=Math.max(17,Math.min(w,h)*.042);circle(d.x,d.y,r,'#ff6678','#ffc0c7',3);ctx.fillStyle='#3a0811';ctx.font=`900 ${Math.max(12,r*.7)}px system-ui`;ctx.textAlign='center';ctx.textBaseline='middle';ctx.fillText('D',d.x,d.y)}
function drawPass(now){const p=state?.t?.pass;if(!p)return;const from=state.t.players[p.from],to=state.t.players[p.to],elapsed=now-p.started,progress=clamp(elapsed/p.duration,0,1),x=from.x+(to.x-from.x)*progress,y=from.y+(to.y-from.y)*progress;ctx.strokeStyle='rgba(255,218,54,.35)';ctx.lineWidth=3;ctx.beginPath();ctx.moveTo(from.x,from.y);ctx.lineTo(to.x,to.y);ctx.stroke();circle(x,y,Math.max(7,Math.min(w,h)*.018),'#ffda36','#fff5b0',2);for(const def of state.t.defenders){if(Math.hypot(def.x-x,def.y-y)<Math.min(w,h)*state.t.d.interceptRadius){finishPass(false,true);return}}if(progress>=1)finishPass(true,false)}
function draw(now=performance.now()){if(!w||!h)return;field();if(state?.t){const dt=lastFrame?Math.min((now-lastFrame)/1000,.035):0;lastFrame=now;moveDefenders(dt);state.t.players.forEach(drawPlayer);state.t.defenders.forEach(drawDefender);if(state.t.phase==='passing')drawPass(now);if(state.t.phase==='choosing'){const remain=clamp(1-(now-state.t.opened)/state.t.d.decisionLimit,0,1);$('#timer i').style.transform=`scaleX(${remain})`}}if($('#game').classList.contains('active'))raf=requestAnimationFrame(draw)}
function header(){if(!session)return;$('#number').textContent=Math.min(session.index+1,TOTAL);$('#bar').style.width=`${session.index/TOTAL*100}%`;$('#level').textContent=session.level;$('#streak').textContent=`STREAK ${session.streak}`}
async function countdown(){for(const x of ['3','2','1']){$('#count').textContent=x;await new Promise(r=>setTimeout(r,380))}$('#count').textContent=''}
async function start(){cancelAnimationFrame(raf);clearTimeout(decisionTimer);const startLevel=clamp(load().level||8,1,MAX_LEVEL);session={index:0,level:startLevel,results:[],block:[],holder:Math.floor(Math.random()*4),streak:0,maxStreak:0};state=null;portraitDismissed=false;show('game');requestAnimationFrame(()=>{resize();header()});$('#feedback').className='feedback';$('#instruction').textContent='守備を見てパス先を選べ';await countdown();launch()}
function launch(){if(!session||session.index>=TOTAL)return finish();clearTimeout(decisionTimer);const t=makeTrial(session.level,session.holder);state={t};lastFrame=performance.now();header();$('#feedback').className='feedback';$('#feedback').textContent='';$('#instruction').textContent='空いた味方をタップ';$('#timer').className='timer show';$('#defenderCount').textContent=`${t.d.defenders} DEFENDER${t.d.defenders>1?'S':''}`;decisionTimer=setTimeout(()=>finishPass(false,false,true),t.d.decisionLimit);cancelAnimationFrame(raf);raf=requestAnimationFrame(draw)}
function tap(e){if(!state||state.t.phase!=='choosing')return;const r=canvas.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top,t=state.t;let chosen=-1,best=Infinity;t.players.forEach((p,i)=>{if(i===t.holder)return;const d=Math.hypot(p.x-x,p.y-y);if(d<best){best=d;chosen=i}});if(chosen<0||best>Math.max(38,Math.min(w,h)*.09))return;clearTimeout(decisionTimer);const from=t.players[t.holder],to=t.players[chosen],distance=Math.hypot(to.x-from.x,to.y-from.y),duration=distance/(Math.min(w,h)*t.d.passSpeed)*1000;t.phase='passing';t.pass={from:t.holder,to:chosen,started:performance.now(),duration};$('#instruction').textContent='パスコースを確認';$('#timer').className='timer'}
function finishPass(success,intercepted=false,timedOut=false){if(!state||state.t.resolved)return;const t=state.t;t.resolved=true;t.phase='done';clearTimeout(decisionTimer);const ms=Math.round(performance.now()-t.opened),f=$('#feedback');f.textContent=timedOut?'TIME OUT':success?'CONNECTED!':'INTERCEPTED';f.className=`feedback show ${success?'good':'bad'}`;$('#instruction').textContent=success?'次の守備を見ろ':timedOut?'判断が遅い':'守備に読まれた';if(success){session.streak++;session.maxStreak=Math.max(session.maxStreak,session.streak);session.holder=t.pass.to}else session.streak=0;session.results.push({success,intercepted,timedOut,ms,defenders:t.d.defenders,level:t.d.level});session.block.push(success);if(session.block.length===4){const c=session.block.filter(Boolean).length;if(c>=3)session.level=clamp(session.level+1,1,MAX_LEVEL);else if(c<=1)session.level=clamp(session.level-1,1,MAX_LEVEL);session.block=[]}header();setTimeout(next,success?520:850)}
function next(){if(!session)return;session.index++;session.index>=TOTAL?finish():launch()}
function median(a){if(!a.length)return 0;a=[...a].sort((x,y)=>x-y);const m=Math.floor(a.length/2);return a.length%2?a[m]:(a[m-1]+a[m])/2}
function rateFor(defenders){const a=session.results.filter(x=>x.defenders===defenders);return a.length?Math.round(a.filter(x=>x.success).length/a.length*100):null}
function finish(){cancelAnimationFrame(raf);clearTimeout(decisionTimer);const score=session.results.filter(x=>x.success).length,valid=session.results.filter(x=>!x.timedOut),ms=Math.round(median(valid.map(x=>x.ms))),turnovers=TOTAL-score,endLevel=session.level,isBest=save(score,endLevel);$('#score').textContent=score;$('#reaction').textContent=valid.length?`${ms} ms`:'-- ms';$('#endLevel').textContent=`Lv.${endLevel}`;$('#maxStreak').textContent=`${session.maxStreak}本`;$('#turnovers').textContent=`${turnovers}回`;$('#message').textContent=score>=18?'ELITE。守備の寄せを外し続けています。':score>=15?'高水準。逆側の空きも早く捉えられています。':score>=11?'判断は成立。ボールを持ってから探さないようにしよう。':'保持者だけでなく、守備と次の受け手を同時に見よう。';$('#passRates').innerHTML=[1,2].map(n=>{const rate=rateFor(n);return`<div><span>${n} DEFENDER${n>1?'S':''}</span><strong>${rate===null?'--':rate+'%'}</strong></div>`}).join('')+`<div><span>MAX STREAK</span><strong>${session.maxStreak}</strong></div>`;$('#newBest').hidden=!isBest;state=null;show('result');refreshStats()}
function home(){cancelAnimationFrame(raf);clearTimeout(decisionTimer);session=null;state=null;show('home');refreshStats()}
function refreshPortrait(){const p=innerHeight>innerWidth&&innerWidth<720&&!portraitDismissed&&$('#game').classList.contains('active');$('#portrait').style.display=p?'flex':'none'}
$('#start').onclick=start;$('#retry').onclick=start;$('#homeBtn').onclick=home;$('#quit').onclick=()=>{if(confirm('トレーニングを終了しますか？'))home()};$('#continue').onclick=()=>{portraitDismissed=true;refreshPortrait()};canvas.addEventListener('pointerdown',tap);addEventListener('resize',()=>{refreshPortrait();if($('#game').classList.contains('active'))resize()});addEventListener('orientationchange',()=>setTimeout(()=>{portraitDismissed=false;refreshPortrait();resize()},200));refreshStats();
